# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='body',
            new_name='product_discount',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='title',
            new_name='product_title',
        ),
        migrations.AddField(
            model_name='note',
            name='product_store',
            field=models.TextField(default='Flipkart'),
        ),
    ]
