# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171218_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='product_discount',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='note',
            name='product_store',
        ),
        migrations.RemoveField(
            model_name='note',
            name='product_title',
        ),
        migrations.AddField(
            model_name='note',
            name='time',
            field=models.TextField(default='Flipkart'),
        ),
    ]
